name: Deploy
on:
    push:
        branches:
            - production
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
            tags:
                description: "수동 빌드"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: tailscale/github-action@v3
              name: Connect to Tailscale network
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:webserver

            - name: Setup SSH Key
              run: |
                  mkdir -p ~/.ssh
                  MACHINE_IP="$(tailscale ip -6 web-server)"
                  ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts

            - uses: actions/checkout@v3
              name: Clone repository
              
            - name: build docker image
              run: |
                  docker build -t mafu-karaoke-pray -f dockerfile .
                  docker image save mafu-karaoke-pray:latest -o ./mafu-karaoke-pray.tar
                  chmod 664 ./mafu-karaoke-pray.tar

            - name: Upload docker image
              run: scp -o StrictHostKeyChecking=no -v ./mafu-karaoke-pray.tar bass9030@web-server:/tmp

            - name: Restarting service
              run: |
                  ssh -o StrictHostKeyChecking=no bass9030@web-server
                  docker-compose -f /home/bass9030/mafu-karaoke-pray/docker-compose.yml down
                  docker rmi -f $(docker images -aq "mafu-karaoke-pray")
                  docker load --input /tmp/mafu-karaoke-pray.tar
                  docker-compose -f /home/bass9030/mafu-karaoke-pray/docker-compose.yml --env-file /home/bass9030/mafu-karaoke-pray/.env up -d
                  rm /tmp/mafu-karaoke-pray.tar
                  exit
